#!/usr/bin/env bash
# Infinite loop creates file with pid

count=1

PIDFILE="/var/run/holbertonscript.pid"
touch $PIDFILE
echo $$ > $PIDFILE

trap 'echo I hate the kill command; rm $PIDFILE; kill -SIGKILL $$' SIGTERM
trap 'echo Y U no love me?!; kill -SIGKILL $$' SIGINT

trap 'rm $PIDFILE; kill -SIGKILL $$' SIGQUIT

while [ $count ]
do
    echo "To infinity and beyond"
    sleep 2
done
