#!/usr/bin/env bash
# Infinite loop creates file with pid

echo "$$" > /var/run/holbertonscript.pid

termfunc() {
    rm /var/run/holbertonscript.pid
    exit
}


while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && termfunc' SIGTERM
    trap 'termfunc' SIGQUIT
done
