#!/usr/bin/env bash
# displays Best School 10 times.

COUNTER=1
while [ $((++COUNTER)) -lt 11 ]
do
    if [ $COUNTER = 5 ]
    then
	echo "bad luck"
    elif [ $COUNTER = 9 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi

done
