#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.
HOURS=-1
while [ $((++HOURS)) -lt 12 ]
do
    echo "Hour: $HOURS"
    MINUTES=0
    while [ $((++MINUTES)) -lt 59 ]
    do
	echo $MINUTES
    done
done
