#!/usr/bin/env bash
# Fix the container so that Nginx is running as the nginx user
pkill -f apache2
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
